// Mocks generated by Mockito 5.4.4 from annotations
// in keysoctest/test/features/iTunes/data/repository/itunes_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:keysoctest/features/iTunes/data/datasources/itunes_remote_datasource.dart'
    as _i2;
import 'package:keysoctest/features/iTunes/data/models/track_model.dart' as _i4;
import 'package:keysoctest/features/iTunes/domain/usecase/itunes_search_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ItunesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockItunesRemoteDataSource extends _i1.Mock
    implements _i2.ItunesRemoteDataSource {
  @override
  _i3.Future<List<_i4.TrackModel>> search(_i5.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [params],
        ),
        returnValue: _i3.Future<List<_i4.TrackModel>>.value(<_i4.TrackModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TrackModel>>.value(<_i4.TrackModel>[]),
      ) as _i3.Future<List<_i4.TrackModel>>);
}
